extends RefCounted

enum ConditionType {
	NONE = 0,
	ADJACENT_SYMBOL_COUNT = 1,
	COUNTER_TRIGGER = 2,
	COMBINED_CONDITION = 3,
	PROBABILITY_CONDITION = 4,
	ANY_TERRAIN_CONDITION = 5,
	MULTIPLE_SYMBOL_CONDITION = 6,
}

enum EffectType {
	ADD_FOOD = 1,
	ADD_EXPERIENCE = 2,
	SPAWN_SYMBOL = 3,
	REMOVE_SELF = 4,
	INCREASE_VARIABLE = 5,
}
